# Generated by Django 3.2 on 2024-11-03 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('PLANO', 'Plano'), ('CONTRATO', 'Contrato'), ('PERMISO', 'Permiso'), ('RENDER', 'Render'), ('ACUERDO', 'Acuerdo'), ('OTRO', 'Otro')], max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
