# Generated by Django 5.1.2 on 2024-11-04 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_historialactividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialactividad',
            name='documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='documentos.documento'),
        ),
    ]
