# Generated by Django 5.1.2 on 2024-11-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0012_remove_reportehistorial_tipo_reporte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportehistorial',
            name='tipo_reporte',
            field=models.CharField(default='PDF', max_length=10),
        ),
    ]
