# Generated by Django 5.1.2 on 2025-03-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0013_reportehistorial_tipo_reporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('progreso', models.FloatField(default=0.0)),
                ('presupuesto_estimado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('presupuesto_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('EN_PROGRESO', 'En Progreso'), ('FINALIZADO', 'Finalizado'), ('PAUSADO', 'Pausado'), ('CANCELADO', 'Cancelado')], default='EN_PROGRESO', max_length=20)),
            ],
        ),
    ]
