# Generated by Django 5.1.2 on 2025-03-25 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0014_obra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10),
        ),
        migrations.AddField(
            model_name='documento',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='REVISION', max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('PLANO', 'Plano'), ('CONTRATO', 'Contrato'), ('PERMISO', 'Permiso'), ('RENDER', 'Render'), ('ACUERDO', 'Acuerdo'), ('ESPECIFICACION', 'Especificación Técnica'), ('MEMORIA', 'Memoria de Cálculo'), ('INFORME', 'Informe Técnico'), ('OTRO', 'Otro')], default='OTRO', max_length=50),
        ),
        migrations.AlterField(
            model_name='documento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historialactividad',
            name='accion',
            field=models.CharField(choices=[('CREACION', 'Creación'), ('EDICION', 'Edición'), ('ELIMINACION', 'Eliminación'), ('APROBACION', 'Aprobación'), ('RECHAZO', 'Rechazo')], max_length=20),
        ),
    ]
