# Generated by Django 5.1.2 on 2025-03-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0015_documento_fecha_actualizacion_documento_prioridad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-fecha_inicio']},
        ),
        migrations.AlterModelOptions(
            name='subcategoria',
            options={'ordering': ['categoria__nombre', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='categoria',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='versiondocumento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='documento',
            unique_together={('titulo', 'proyecto')},
        ),
    ]
