# Generated by Django 5.1.2 on 2025-03-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0016_alter_categoria_options_alter_documento_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documento',
            unique_together=set(),
        ),
    ]
