# Generated by Django 5.1.2 on 2025-03-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0017_alter_documento_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='documentos.categoria'),
        ),
    ]
