# Generated by Django 5.1.2 on 2025-04-01 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0018_proyecto_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='subcategoria',
        ),
        migrations.DeleteModel(
            name='Subcategoria',
        ),
    ]
