# Generated by Django 5.1.2 on 2025-06-16 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0021_alter_historialactividad_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialactividad',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.documento'),
        ),
    ]
