# Generated by Django 5.1.2 on 2025-06-16 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0022_alter_historialactividad_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialactividad',
            name='documento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='documentos.documento'),
            preserve_default=False,
        ),
    ]
