# Generated by Django 5.1.2 on 2025-06-16 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0024_alter_historialactividad_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='documentos.categoria'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='documentos.proyecto'),
        ),
    ]
