# Generated by Django 5.1.2 on 2025-06-16 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0025_alter_documento_categoria_alter_documento_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialactividad',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='documentos.documento'),
        ),
    ]
