# Generated by Django 5.1.2 on 2025-03-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20241104_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='puede_gestionar_costos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_gestionar_reportes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_gestionar_usuarios',
            field=models.BooleanField(default=False),
        ),
    ]
