# Generated by Django 5.1.2 on 2025-03-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rol_puede_gestionar_costos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.JSONField(default=dict),
        ),
    ]
