# Generated by Django 5.1.2 on 2025-06-01 05:59

import django.db.models.deletion
import prediccion.models.cotizacion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0020_alter_historialactividad_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('modelo_lstm', models.FileField(upload_to='modelos_lstm/')),
                ('csv_datos', models.FileField(upload_to='datasets_productos/')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total_general', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_prediccion', models.DateTimeField(auto_now=True)),
                ('fecha_validez', models.DateTimeField(default=prediccion.models.cotizacion.obtener_fecha_validez)),
                ('tipo_cambio_dolar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_cambio_origen', models.CharField(choices=[('Oficial', 'Oficial'), ('Paralelo', 'Paralelo')], default='Oficial', max_length=20)),
                ('tipo_cambio_valor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='documentos.categoria')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='documentos.proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrediccionHistorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_estimado_bs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_estimado_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tipo_cambio_utilizado', models.DecimalField(decimal_places=4, max_digits=10)),
                ('tipo_cambio_origen', models.CharField(choices=[('Oficial', 'Oficial'), ('Paralelo', 'Paralelo')], default='Oficial', max_length=20)),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicciones_registradas', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='prediccion.producto')),
            ],
            options={
                'ordering': ['-fecha_prediccion'],
            },
        ),
        migrations.CreateModel(
            name='ProductoCotizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_cotizados', to='prediccion.cotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prediccion.producto')),
            ],
        ),
    ]
