# Generated by Django 5.1.2 on 2025-04-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='total_general',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
