# Generated by Django 5.1.2 on 2025-06-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloTipoCambioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('modelo_file', models.FileField(upload_to='modelos_tipo_cambio/')),
                ('csv_dataset_file', models.FileField(upload_to='datasets_tipo_cambio/')),
                ('tipo_cambio_origen', models.CharField(choices=[('Oficial', 'Oficial'), ('Paralelo', 'Paralelo')], max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PrediccionTipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prediccion', models.DateField(auto_now_add=True)),
                ('horizonte_dias', models.IntegerField()),
                ('tipo_cambio_origen', models.CharField(choices=[('Oficial', 'Oficial'), ('Paralelo', 'Paralelo')], max_length=20)),
                ('prediccion_json', models.JSONField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('nombre_modelo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCambioHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('tipo_cambio_oficial', models.FloatField(blank=True, null=True)),
                ('tipo_cambio_paralelo', models.FloatField(blank=True, null=True)),
                ('fuente', models.CharField(default='api', max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
