# Generated by Django 5.1.2 on 2025-06-08 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0002_modelotipocambioconfig_predicciontipocambio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionFutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Simulación futura', max_length=255)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('dolar_usado', models.FloatField()),
                ('total_bs', models.FloatField()),
                ('productos_simulados', models.JSONField()),
                ('cotizacion_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulaciones_futuras', to='prediccion.cotizacion')),
            ],
        ),
    ]
