# Generated by Django 5.1.2 on 2025-05-07 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0002_alter_cotizacion_total_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_prediccion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_validez',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 14, 17, 8, 50, 808568, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tipo_cambio_dolar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
