# Generated by Django 5.1.2 on 2025-05-07 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0003_cotizacion_fecha_prediccion_cotizacion_fecha_validez_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_validez',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 14, 17, 23, 35, 692221, tzinfo=datetime.timezone.utc)),
        ),
    ]
