# Generated by Django 5.1.2 on 2025-06-08 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0003_cotizacionfutura'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionfutura',
            name='categoria_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cotizacionfutura',
            name='proyecto_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cotizacionfutura',
            name='tipo_cambio_origen',
            field=models.CharField(default='Paralelo', max_length=50),
        ),
        migrations.CreateModel(
            name='ProductoCotizadoFuturo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cotizacion_futura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_cotizados', to='prediccion.cotizacionfutura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prediccion.producto')),
            ],
        ),
    ]
