# Generated by Django 5.1.2 on 2025-06-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0004_cotizacionfutura_categoria_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionfutura',
            name='horizonte_dias',
            field=models.IntegerField(default=0),
        ),
    ]
