# Generated by Django 5.1.2 on 2025-05-08 00:40

import prediccion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0004_alter_cotizacion_fecha_validez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_validez',
            field=models.DateTimeField(default=prediccion.models.obtener_fecha_validez),
        ),
    ]
