# Generated by Django 5.1.2 on 2025-05-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0005_alter_cotizacion_fecha_validez'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='tipo_cambio_origen',
            field=models.CharField(choices=[('Oficial', 'Oficial'), ('Paralelo', 'Paralelo')], default='Oficial', max_length=20),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tipo_cambio_valor',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
