# Generated by Django 5.1.2 on 2025-06-12 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0005_cotizacionfutura_horizonte_dias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('unidad', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_adicionales', to='prediccion.cotizacion')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDolarSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('tipo_cambio_origen', models.CharField(choices=[('Oficial', 'Oficial'), ('Paralelo', 'Paralelo')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fuente', models.CharField(default='Sistema', max_length=100)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('agregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
