# Generated by Django 5.1.2 on 2025-06-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0006_itemadicional_registrodolarsistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='contingencia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='gastos_generales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='utilidad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
