# Generated by Django 5.1.2 on 2025-05-25 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0006_cotizacion_tipo_cambio_origen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrediccionHistorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_estimado_bs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_estimado_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tipo_cambio_utilizado', models.DecimalField(decimal_places=4, max_digits=10)),
                ('tipo_cambio_origen', models.CharField(choices=[('Oficial', 'Oficial'), ('Paralelo', 'Paralelo')], default='Oficial', max_length=20)),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='prediccion.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_prediccion'],
            },
        ),
    ]
