# Generated by Django 5.1.2 on 2025-05-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0007_prediccionhistorica'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='precision',
            field=models.FloatField(default=0.0),
        ),
    ]
