# Generated by Django 5.1.2 on 2025-06-15 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0020_alter_historialactividad_documento'),
        ('prediccion', '0008_proforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='documentos.obra'),
        ),
    ]
