# Generated by Django 5.1.2 on 2025-05-26 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0008_cotizacion_precision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='precision',
        ),
    ]
